apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argo_files/non_prod
    repoURL: https://github.com/slaterin/argocd_workshop
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
